# -*- coding: utf-8 -*-
"""MarkovChained-DPWorldHackathon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9jPWv6yslXWk8bHGsHbpfEpFI6cpoM7
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("bertnardomariouskono/global-supply-chain-disruption-and-resilience")

print("Path to dataset files:", path)

import os

print(os.listdir(path))

import pandas as pd

file_path = os.path.join(path, 'global_supply_chain_disruption_v1.csv')
df = pd.read_csv(file_path)

df.head()

df.info()
df.describe()

df.isnull().sum()

"""## EDA + Disruption_Event Encoding"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# ── Load ──────────────────────────────────────────────────────────────────────
file_path = os.path.join(path, 'global_supply_chain_disruption_v1.csv')
df = pd.read_csv(file_path)

print("Shape:", df.shape)
print("\nDelivery_Status distribution:")
print(df['Delivery_Status'].value_counts())
print("\nDelay_Days stats:")
print(df['Delay_Days'].describe())

# ── Disruption_Event: fill nulls → encode ordinal 0-3 ─────────────────────────
# None=0 (no event), Port Congestion=1, Severe Weather=2, Geopolitical=3
df['Disruption_Event'] = df['Disruption_Event'].fillna('None')

disruption_map = {
    'None': 0,
    'Port Congestion': 1,
    'Severe Weather': 2,
    'Geopolitical Conflict': 3
}
df['Disruption_Event_Enc'] = df['Disruption_Event'].map(disruption_map)
# Catch any unseen labels gracefully
df['Disruption_Event_Enc'] = df['Disruption_Event_Enc'].fillna(0).astype(int)

print("\nDisruption_Event distribution after encoding:")
print(df['Disruption_Event'].value_counts())

# ── Target variable ───────────────────────────────────────────────────────────
df['is_delayed'] = (df['Delay_Days'] > 0).astype(int)
print(f"\nClass balance — Delayed: {df['is_delayed'].sum()} | On Time: {(df['is_delayed']==0).sum()}")
print(f"Delay rate: {df['is_delayed'].mean():.2%}")

# ── Quick visual EDA ──────────────────────────────────────────────────────────
fig, axes = plt.subplots(2, 3, figsize=(16, 9))

# 1. Delay rate by Route_Type
delay_by_route = df.groupby('Route_Type')['is_delayed'].mean().sort_values(ascending=False)
axes[0,0].bar(delay_by_route.index, delay_by_route.values, color='#e74c3c')
axes[0,0].set_title('Delay Rate by Route Type')
axes[0,0].set_ylabel('Delay Rate')

# 2. Weather_Severity_Index distribution: delayed vs not
axes[0,1].hist(df[df['is_delayed']==0]['Weather_Severity_Index'], bins=30, alpha=0.6, label='On Time', color='#2ecc71')
axes[0,1].hist(df[df['is_delayed']==1]['Weather_Severity_Index'], bins=30, alpha=0.6, label='Delayed', color='#e74c3c')
axes[0,1].set_title('Weather Severity: Delayed vs On Time')
axes[0,1].legend()

# 3. Geopolitical_Risk_Index vs Delay_Days scatter
axes[0,2].scatter(df['Geopolitical_Risk_Index'], df['Delay_Days'], alpha=0.1, color='#3498db', s=5)
axes[0,2].set_title('Geopolitical Risk vs Delay Days')
axes[0,2].set_xlabel('Geopolitical Risk Index')
axes[0,2].set_ylabel('Delay Days')

# 4. Disruption_Event breakdown
axes[1,0].bar(disruption_map.keys(), df['Disruption_Event'].value_counts().reindex(disruption_map.keys()).values,
              color=['#95a5a6','#e67e22','#3498db','#e74c3c'])
axes[1,0].set_title('Disruption Event Frequency')

# 5. Mitigation_Action_Taken (RL target reference)
mit_counts = df['Mitigation_Action_Taken'].value_counts()
axes[1,1].barh(mit_counts.index, mit_counts.values, color='#9b59b6')
axes[1,1].set_title('Mitigation Actions (RL Reference)')

# 6. Delay_Days histogram
axes[1,2].hist(df[df['Delay_Days']>0]['Delay_Days'], bins=20, color='#e74c3c', edgecolor='white')
axes[1,2].set_title('Delay Days Distribution (Delayed Only)')
axes[1,2].set_xlabel('Days')

plt.tight_layout()
plt.show()

"""## Feature Engineering + Corridor Mapping + Train/Test Split"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# ── Encode categoricals ───────────────────────────────────────────────────────
le = LabelEncoder()

df['Transportation_Mode_Enc'] = le.fit_transform(df['Transportation_Mode'])  # Air=0, Sea=1

route_map = {'Atlantic': 0, 'Intra-Asia': 1, 'Pacific': 2, 'Suez': 3}
df['Route_Type_Enc'] = df['Route_Type'].map(route_map).fillna(0).astype(int)

# ── Corridor ID: map Route_Type → your 4 demo corridors ─────────────────────
# This bridges the dataset to your actual port nodes in the RL agent
corridor_map = {
    'Intra-Asia': 0,   # Singapore → Colombo
    'Suez':       1,   # Singapore → Jebel Ali
    'Pacific':    2,   # Singapore → Mundra (proxy)
    'Atlantic':   3    # Singapore → Nhava Sheva (proxy)
}
df['Corridor_ID'] = df['Route_Type'].map(corridor_map).fillna(0).astype(int)

# ── Weather state buckets (used by RL agent) ──────────────────────────────────
# Mirrors the 3 weather states in your Q-table schema
def bucket_weather(x):
    if x < 0.33:   return 0  # Clear
    elif x < 0.66: return 1  # Moderate
    else:          return 2  # Severe

df['Weather_State'] = df['Weather_Severity_Index'].apply(bucket_weather)

# ── Congestion level (used by RL agent) ───────────────────────────────────────
# 2-level: Low=0, High=1 — based on geopolitical + disruption combined score
df['Congestion_Score'] = (df['Geopolitical_Risk_Index'] + df['Disruption_Event_Enc'] / 3) / 2
df['Congestion_Level'] = (df['Congestion_Score'] > 0.5).astype(int)

# ── Final feature set for XGBoost ─────────────────────────────────────────────
FEATURE_COLS = [
    'Geopolitical_Risk_Index',
    'Weather_Severity_Index',
    'Inflation_Rate_Pct',
    'Base_Lead_Time_Days',
    'Transportation_Mode_Enc',
    'Route_Type_Enc',
    'Disruption_Event_Enc',
    'Order_Weight_Kg',
    'Congestion_Score'
]
TARGET_COL = 'is_delayed'

X = df[FEATURE_COLS]
y = df[TARGET_COL]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train: {X_train.shape} | Test: {X_test.shape}")
print(f"Train delay rate: {y_train.mean():.2%} | Test delay rate: {y_test.mean():.2%}")

# ── Correlation heatmap ───────────────────────────────────────────────────────
plt.figure(figsize=(10, 7))
corr = df[FEATURE_COLS + [TARGET_COL]].corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', center=0)
plt.title('Feature Correlation with is_delayed')
plt.tight_layout()
plt.show()

"""## XGBoost Training + Evaluation"""

import xgboost as xgb
from sklearn.metrics import (classification_report, roc_auc_score,
                             confusion_matrix, RocCurveDisplay)
import pickle

# ── Train ─────────────────────────────────────────────────────────────────────
model = xgb.XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=(y_train==0).sum() / (y_train==1).sum(),  # handles class imbalance
    use_label_encoder=False,
    eval_metric='auc',
    random_state=42,
    early_stopping_rounds=20
)

model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    verbose=50
)

# ── Evaluate ──────────────────────────────────────────────────────────────────
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]  # congestion_probability output

print("\n── Classification Report ──")
print(classification_report(y_test, y_pred, target_names=['On Time', 'Delayed']))
print(f"ROC-AUC: {roc_auc_score(y_test, y_prob):.4f}")

# ── Plots ─────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', ax=axes[0], cmap='Blues',
            xticklabels=['On Time','Delayed'], yticklabels=['On Time','Delayed'])
axes[0].set_title('Confusion Matrix')

# Feature importance
xgb.plot_importance(model, ax=axes[1], max_num_features=9, importance_type='gain')
axes[1].set_title('Feature Importance (Gain)')

# ROC curve
RocCurveDisplay.from_predictions(y_test, y_prob, ax=axes[2])
axes[2].set_title('ROC Curve')

plt.tight_layout()
plt.show()

# ── Attach congestion_probability back to df (RL needs it) ────────────────────
df['congestion_probability'] = model.predict_proba(df[FEATURE_COLS])[:, 1]

# ── Save model ────────────────────────────────────────────────────────────────
with open('xgb_congestion_model.pkl', 'wb') as f:
    pickle.dump(model, f)
print("\nModel saved → xgb_congestion_model.pkl")

"""## RL Environment (MDP Definition)"""

import numpy as np
import random

class SupplyChainEnv:
    """
    MDP for the Q-Learning RL agent.
    State  : (corridor_id [0-3], weather_state [0-2], congestion_level [0-1])
             → 4 × 3 × 2 = 24 discrete states
    Action : 0=Maintain Course | 1=Slow Steam | 2=Reroute
    Reward : R = -(ω₁·ΔT + ω₂·ΔC + ω₃·ΔE)  (from slide 6)
    """

    # Weights from your reward function (tunable)
    W_TIME   = 0.4   # ω₁
    W_COST   = 0.35  # ω₂
    W_CARBON = 0.25  # ω₃

    # Action cost profiles — (ΔT_hours, ΔCost_USD, ΔCarbon_tCO2)
    # These are normalised per-reroute estimates based on your slide numbers
    ACTION_PROFILES = {
        0: {'dt': 0.0,  'dc': 0.0,    'de': 0.0  },  # Maintain Course  — no change
        1: {'dt': 2.0,  'dc': 3000.0, 'de': 2.5  },  # Slow Steam       — moderate
        2: {'dt': -4.2, 'dc': -12400, 'de': -8.6 },  # Reroute          — best case from slide 5
    }

    def __init__(self, df):
        self.df = df.copy()
        self.episodes = self._build_episodes()
        self.n_states  = 4 * 3 * 2   # 24
        self.n_actions = 3

    def _build_episodes(self):
        """Each row in df becomes one episode with a defined state."""
        episodes = []
        for _, row in self.df.iterrows():
            state = self._encode_state(
                int(row['Corridor_ID']),
                int(row['Weather_State']),
                int(row['Congestion_Level'])
            )
            congestion_prob = row['congestion_probability']
            actual_delay    = row['Delay_Days']
            mitigation_ref  = row['Mitigation_Action_Taken']  # ground truth reference
            episodes.append((state, congestion_prob, actual_delay, mitigation_ref))
        return episodes

    def _encode_state(self, corridor, weather, congestion):
        """Map (corridor, weather, congestion) → single integer state index."""
        return corridor * 6 + weather * 2 + congestion

    def decode_state(self, s):
        """Reverse: integer → (corridor, weather, congestion)."""
        corridor   = s // 6
        remainder  = s % 6
        weather    = remainder // 2
        congestion = remainder % 2
        return corridor, weather, congestion

    def compute_reward(self, action, congestion_prob, actual_delay):
        """
        R = -(ω₁·ΔT + ω₂·ΔC_norm + ω₃·ΔE_norm)
        Scale cost and carbon to [0,1] range so weights are comparable to time.
        Higher congestion_prob → wrong action is penalised more.
        """
        profile = self.ACTION_PROFILES[action]
        dt      = profile['dt']
        dc      = profile['dc'] / 15000.0   # normalise to ~[-1, 1]
        de      = profile['de'] / 10.0      # normalise

        base_reward = -(self.W_TIME * dt + self.W_COST * dc + self.W_CARBON * de)

        # Penalty: if congestion was high and agent chose Maintain Course
        if congestion_prob > 0.6 and action == 0:
            base_reward -= 1.5 * congestion_prob * actual_delay * 0.1

        # Bonus: correct aggressive action when disruption was real
        if congestion_prob > 0.6 and action == 2:
            base_reward += 0.5

        return float(base_reward)

    def sample_episode(self):
        return random.choice(self.episodes)


# ── Instantiate and verify ─────────────────────────────────────────────────────
env = SupplyChainEnv(df)
print(f"Environment ready — States: {env.n_states} | Actions: {env.n_actions}")
print(f"Total episodes available: {len(env.episodes)}")

# Sanity check decode
for s in [0, 7, 23]:
    c, w, cg = env.decode_state(s)
    print(f"  State {s:2d} → Corridor={c} Weather={w} Congestion={cg}")

"""## Q-Learning Training + Q-Table Export"""

import json

# ── Hyperparameters ────────────────────────────────────────────────────────────
ALPHA   = 0.1     # learning rate
GAMMA   = 0.95    # discount factor
EPSILON = 1.0     # starting exploration rate
EPS_MIN = 0.01
EPS_DECAY = 0.995
N_EPISODES = 15000

# ── Q-Table init ───────────────────────────────────────────────────────────────
Q = np.zeros((env.n_states, env.n_actions))

action_labels = {0: 'Maintain Course', 1: 'Slow Steam', 2: 'Reroute'}
reward_history = []

# ── Training loop ──────────────────────────────────────────────────────────────
for ep in range(N_EPISODES):
    state, congestion_prob, actual_delay, _ = env.sample_episode()

    # ε-greedy action selection
    if random.random() < EPSILON:
        action = random.randint(0, env.n_actions - 1)
    else:
        action = np.argmax(Q[state])

    reward = env.compute_reward(action, congestion_prob, actual_delay)

    # Q-update (single-step, no next state needed — episodic MDP)
    Q[state, action] += ALPHA * (reward + GAMMA * np.max(Q[state]) - Q[state, action])

    reward_history.append(reward)
    EPSILON = max(EPS_MIN, EPSILON * EPS_DECAY)

    if (ep + 1) % 3000 == 0:
        avg_r = np.mean(reward_history[-500:])
        print(f"Episode {ep+1:>6} | ε={EPSILON:.4f} | Avg Reward (last 500): {avg_r:.4f}")

print("\nTraining complete.")

# ── Evaluate learned policy ────────────────────────────────────────────────────
print("\n── Optimal Policy per State ──")
corridor_names = {0:'SIN→Colombo', 1:'SIN→JebelAli', 2:'SIN→Mundra', 3:'SIN→NhavaSheva'}
weather_names  = {0:'Clear', 1:'Moderate', 2:'Severe'}
congestion_names = {0:'Low', 1:'High'}

policy_rows = []
for s in range(env.n_states):
    c, w, cg = env.decode_state(s)
    best_action = np.argmax(Q[s])
    q_vals = Q[s]
    policy_rows.append({
        'State': s,
        'Corridor': corridor_names[c],
        'Weather': weather_names[w],
        'Congestion': congestion_names[cg],
        'Optimal_Action': action_labels[best_action],
        'Q_Maintain': round(q_vals[0], 4),
        'Q_SlowSteam': round(q_vals[1], 4),
        'Q_Reroute':   round(q_vals[2], 4),
    })

policy_df = pd.DataFrame(policy_rows)
print(policy_df.to_string(index=False))

# ── Reward convergence plot ────────────────────────────────────────────────────
window = 200
smoothed = pd.Series(reward_history).rolling(window).mean()
plt.figure(figsize=(12, 4))
plt.plot(smoothed, color='#3498db', linewidth=1.5)
plt.title(f'Q-Learning Reward Convergence (rolling {window})')
plt.xlabel('Episode')
plt.ylabel('Avg Reward')
plt.axhline(0, color='grey', linestyle='--', linewidth=0.8)
plt.tight_layout()
plt.show()

# ── Export Q-table as JSON for FastAPI ────────────────────────────────────────
q_table_export = {}
for s in range(env.n_states):
    c, w, cg = env.decode_state(s)
    key = f"{c}_{w}_{cg}"   # "corridor_weather_congestion"
    q_table_export[key] = {
        'state_index': s,
        'corridor': corridor_names[c],
        'weather': weather_names[w],
        'congestion': congestion_names[cg],
        'q_values': {
            'maintain_course': round(float(Q[s, 0]), 6),
            'slow_steam':      round(float(Q[s, 1]), 6),
            'reroute':         round(float(Q[s, 2]), 6),
        },
        'optimal_action': action_labels[int(np.argmax(Q[s]))]
    }

with open('q_table.json', 'w') as f:
    json.dump(q_table_export, f, indent=2)

print("\nQ-table saved → q_table.json")
print("Hand this JSON to the backend team. FastAPI queries it with (corridor, weather, congestion) → returns optimal_action.")

"""## 6. Tweaks"""

# ── Identify unvisited states ─────────────────────────────────────────────────
zero_states = [s for s in range(env.n_states) if np.all(Q[s] == 0.0)]
print(f"Unvisited states: {zero_states}")

def generate_synthetic_episodes(n=5000):
    """
    Fill sparse states by sampling from a physics-informed prior.
    Logic: higher weather/congestion → higher congestion_prob → reroute rewarded more.
    """
    synthetic = []
    for _ in range(n):
        corridor   = random.randint(0, 3)
        weather    = random.randint(0, 2)
        congestion = random.randint(0, 1)

        # Congestion probability proportional to weather + congestion state
        base_prob  = (weather / 2.0) * 0.5 + (congestion * 0.4) + random.gauss(0, 0.05)
        cong_prob  = float(np.clip(base_prob, 0.0, 1.0))

        # Actual delay proportional to prob
        actual_delay = max(0, int(cong_prob * 15 + random.gauss(0, 1)))

        state = env._encode_state(corridor, weather, congestion)
        synthetic.append((state, cong_prob, actual_delay, 'Synthetic'))
    return synthetic

# ── Retrain Q on original + synthetic ────────────────────────────────────────
synthetic_episodes = generate_synthetic_episodes(5000)
all_episodes = env.episodes + synthetic_episodes

print(f"Total episodes after augmentation: {len(all_episodes)}")

# Re-init Q and retrain
Q = np.zeros((env.n_states, env.n_actions))
EPSILON  = 1.0
ALPHA    = 0.1
GAMMA    = 0.95
N_EPISODES_AUG = 20000
reward_history_aug = []

for ep in range(N_EPISODES_AUG):
    state, congestion_prob, actual_delay, _ = random.choice(all_episodes)

    if random.random() < EPSILON:
        action = random.randint(0, env.n_actions - 1)
    else:
        action = np.argmax(Q[state])

    reward = env.compute_reward(action, congestion_prob, actual_delay)
    Q[state, action] += ALPHA * (reward + GAMMA * np.max(Q[state]) - Q[state, action])
    reward_history_aug.append(reward)
    EPSILON = max(0.01, EPSILON * 0.9995)

print("Retraining complete.")

# Verify all states now have non-zero Q-values
still_zero = [s for s in range(env.n_states) if np.all(Q[s] == 0.0)]
print(f"Still-zero states after augmentation: {still_zero if still_zero else 'None ✓'}")

"""## Modular Inference Pipeline (Steps 4 + 5)"""

import pickle, json
import numpy as np

# ── Action metadata for output ────────────────────────────────────────────────
ACTION_META = {
    0: {
        'label':        'Maintain Course',
        'delay_saved':   0.0,
        'cost_saved':    0.0,
        'carbon_saved':  0.0,
    },
    1: {
        'label':        'Slow Steam',
        'delay_saved':   1.5,
        'cost_saved':   3200.0,
        'carbon_saved':  2.5,
    },
    2: {
        'label':        'Reroute',
        'delay_saved':   4.2,
        'cost_saved':  12400.0,
        'carbon_saved':  8.6,
    },
}

CORRIDOR_MAP_INV   = {0:'SIN→Colombo', 1:'SIN→JebelAli', 2:'SIN→Mundra', 3:'SIN→NhavaSheva'}
WEATHER_MAP_INV    = {0:'Clear', 1:'Moderate', 2:'Severe'}
CONGESTION_MAP_INV = {0:'Low', 1:'High'}

# ── Step 1: ML Layer ──────────────────────────────────────────────────────────
def predict_congestion_probability(
    xgb_model,
    corridor_id: int,
    weather_severity_raw: float,   # 0.0–1.0 from Open-Meteo mapping
    geopolitical_risk: float,      # 0.0–1.0
    base_lead_time: int = 12,
    transport_mode_enc: int = 1,   # 1=Sea default
    disruption_event_enc: int = 0, # 0=None at live demo
    order_weight_kg: int = 5000,
    inflation_rate: float = 3.0,
) -> float:
    """
    Run XGBoost to get congestion probability.
    Returns float in [0, 1].
    """
    congestion_score = (geopolitical_risk + disruption_event_enc / 3.0) / 2.0

    features = np.array([[
        geopolitical_risk,
        weather_severity_raw,
        inflation_rate,
        base_lead_time,
        transport_mode_enc,
        corridor_id,          # Route_Type_Enc proxy
        disruption_event_enc,
        order_weight_kg,
        congestion_score,
    ]])

    prob = float(xgb_model.predict_proba(features)[0, 1])
    return round(prob, 4)


# ── Step 2: State Encoder ─────────────────────────────────────────────────────
def encode_rl_state(
    corridor_id: int,
    weather_severity_raw: float,
    congestion_probability: float,
) -> tuple[int, int, int, int]:
    """
    Convert raw inputs to RL state index.
    Returns (state_index, corridor, weather_level, congestion_level).
    """
    # Weather bucketing (mirrors Chunk 2)
    if weather_severity_raw < 0.33:
        weather_level = 0
    elif weather_severity_raw < 0.66:
        weather_level = 1
    else:
        weather_level = 2

    congestion_level = 1 if congestion_probability >= 0.5 else 0

    state_index = corridor_id * 6 + weather_level * 2 + congestion_level
    return state_index, corridor_id, weather_level, congestion_level


# ── Step 3: Q-Table Lookup ────────────────────────────────────────────────────
def query_q_table(Q_table: np.ndarray, state_index: int) -> tuple[int, float]:
    """
    Returns (optimal_action_id, confidence_score).
    Confidence = softmax gap between best and second-best Q-value.
    """
    q_vals = Q_table[state_index]

    # Softmax for confidence
    exp_q   = np.exp(q_vals - np.max(q_vals))
    softmax = exp_q / exp_q.sum()

    optimal_action = int(np.argmax(q_vals))
    confidence     = float(softmax[optimal_action])
    return optimal_action, confidence


# ── Step 4: Full Inference Pipeline ──────────────────────────────────────────
def run_inference(
    xgb_model,
    Q_table: np.ndarray,
    corridor_id: int,
    weather_severity_raw: float,
    geopolitical_risk: float,
    **kwargs
) -> dict:
    """
    End-to-end: raw inputs → JSON decision output.

    Returns:
    {
        action, confidence, congestion_probability,
        delay_saved, cost_saved, carbon_saved,
        state_description, q_values
    }
    """
    # Step 1: ML prediction
    cong_prob = predict_congestion_probability(
        xgb_model,
        corridor_id,
        weather_severity_raw,
        geopolitical_risk,
        **kwargs
    )

    # Step 2: RL state
    state_idx, corridor, weather_level, cong_level = encode_rl_state(
        corridor_id, weather_severity_raw, cong_prob
    )

    # Step 3: Q-table lookup
    action_id, confidence = query_q_table(Q_table, state_idx)
    meta = ACTION_META[action_id]

    # Step 5: Explainability payload
    output = {
        # Core decision
        'action':                meta['label'],
        'confidence':            round(confidence, 4),

        # ML output
        'congestion_probability': cong_prob,
        'congestion_level':      CONGESTION_MAP_INV[cong_level],

        # ROI metrics (from slide 5 values, scaled by probability)
        'delay_saved_hours':     round(meta['delay_saved'] * (cong_prob + 0.3), 2),
        'cost_saved_usd':        round(meta['cost_saved']  * (cong_prob + 0.3), 2),
        'carbon_saved_tco2':     round(meta['carbon_saved']* (cong_prob + 0.3), 2),

        # State description (for frontend panel)
        'state': {
            'index':      state_idx,
            'corridor':   CORRIDOR_MAP_INV[corridor],
            'weather':    WEATHER_MAP_INV[weather_level],
            'congestion': CONGESTION_MAP_INV[cong_level],
        },

        # Raw Q-values (for frontend confidence bar)
        'q_values': {
            'Maintain Course': round(float(Q[state_idx, 0]), 4),
            'Slow Steam':      round(float(Q[state_idx, 1]), 4),
            'Reroute':         round(float(Q[state_idx, 2]), 4),
        }
    }
    return output

# ── Name alignment fix ────────────────────────────────────────────────────────
xgb_model = model  # model was trained in Chunk 3 as 'model'

# ── Chunk 6 verification output ───────────────────────────────────────────────
zero_states_before = [s for s in range(env.n_states) if np.all(Q[s] == 0.0)]
print(f"Zero states BEFORE augmentation: {zero_states_before}")
print(f"Count: {len(zero_states_before)} / {env.n_states}")

# Re-run augmentation with output
synthetic_episodes = generate_synthetic_episodes(5000)
all_episodes = env.episodes + synthetic_episodes
print(f"\nOriginal episodes : {len(env.episodes)}")
print(f"Synthetic episodes: {len(synthetic_episodes)}")
print(f"Total             : {len(all_episodes)}")

# Retrain
Q = np.zeros((env.n_states, env.n_actions))
EPSILON = 1.0
reward_history_aug = []

for ep in range(20000):
    state, congestion_prob, actual_delay, _ = random.choice(all_episodes)
    if random.random() < EPSILON:
        action = random.randint(0, env.n_actions - 1)
    else:
        action = np.argmax(Q[state])
    reward = env.compute_reward(action, congestion_prob, actual_delay)
    Q[state, action] += 0.1 * (reward + 0.95 * np.max(Q[state]) - Q[state, action])
    reward_history_aug.append(reward)
    EPSILON = max(0.01, EPSILON * 0.9995)

zero_states_after = [s for s in range(env.n_states) if np.all(Q[s] == 0.0)]
print(f"\nZero states AFTER augmentation : {zero_states_after if zero_states_after else 'None ✓'}")
print(f"Retraining complete — Q-table updated in memory")

# Show updated policy for the 3 key demo states
print("\n── Spot-check: Key Demo States ──")
demo_check = [
    (1, 2, 1, "SIN→JebelAli | Severe | High"),   # should → Reroute
    (0, 1, 0, "SIN→Colombo  | Moderate | Low"),   # should → Slow Steam or Maintain
    (2, 0, 0, "SIN→Mundra   | Clear | Low"),       # should → Maintain Course
]
for c, w, cg, label in demo_check:
    s = env._encode_state(c, w, cg)
    best = int(np.argmax(Q[s]))
    print(f"  {label:40s} → {ACTION_META[best]['label']}  Q={np.round(Q[s],3)}")

"""##  Baseline Comparison (Step 6)"""

# ── Static baseline policy: always Maintain Course ───────────────────────────
def baseline_policy(_state_idx: int) -> int:
    return 0  # Always Maintain Course

def run_baseline_comparison(xgb_model, Q_table, test_scenarios: list[dict]) -> dict:
    """
    Compare RL policy vs static baseline across N test scenarios.
    Returns aggregate performance delta.
    """
    rl_rewards, base_rewards = [], []
    rl_costs_saved, base_costs_saved = [], []
    rl_carbon_saved, base_carbon_saved = [], []
    correct_actions = 0

    for scenario in test_scenarios:
        cong_prob = predict_congestion_probability(
            xgb_model,
            scenario['corridor_id'],
            scenario['weather_severity_raw'],
            scenario['geopolitical_risk'],
        )
        state_idx, _, _, cong_level = encode_rl_state(
            scenario['corridor_id'],
            scenario['weather_severity_raw'],
            cong_prob
        )
        actual_delay = scenario.get('actual_delay', int(cong_prob * 10))

        rl_action,   _ = query_q_table(Q_table, state_idx)
        base_action     = baseline_policy(state_idx)

        rl_r   = env.compute_reward(rl_action,   cong_prob, actual_delay)
        base_r = env.compute_reward(base_action, cong_prob, actual_delay)

        rl_rewards.append(rl_r)
        base_rewards.append(base_r)
        rl_costs_saved.append(ACTION_META[rl_action]['cost_saved'])
        base_costs_saved.append(ACTION_META[base_action]['cost_saved'])
        rl_carbon_saved.append(ACTION_META[rl_action]['carbon_saved'])
        base_carbon_saved.append(ACTION_META[base_action]['carbon_saved'])

        # Count when RL correctly chose non-Maintain on disrupted scenarios
        if cong_prob > 0.5 and rl_action != 0:
            correct_actions += 1

    n = len(test_scenarios)
    results = {
        'n_scenarios': n,
        'rl_avg_reward':        round(np.mean(rl_rewards), 4),
        'baseline_avg_reward':  round(np.mean(base_rewards), 4),
        'reward_delta':         round(np.mean(rl_rewards) - np.mean(base_rewards), 4),
        'rl_total_cost_saved':  round(sum(rl_costs_saved), 2),
        'baseline_total_cost_saved': round(sum(base_costs_saved), 2),
        'rl_total_carbon_saved': round(sum(rl_carbon_saved), 2),
        'baseline_total_carbon_saved': round(sum(base_carbon_saved), 2),
        'correct_intervention_rate': round(correct_actions / max(1, sum(1 for s in test_scenarios
                                      if predict_congestion_probability(
                                          xgb_model, s['corridor_id'],
                                          s['weather_severity_raw'], s['geopolitical_risk']
                                      ) > 0.5)), 4)
    }
    return results


# ── Generate test scenarios from held-out data ────────────────────────────────
test_sample = df[df['is_delayed'] == 1].sample(200, random_state=42)
test_scenarios = [
    {
        'corridor_id':          int(row['Corridor_ID']),
        'weather_severity_raw': float(row['Weather_Severity_Index']),
        'geopolitical_risk':    float(row['Geopolitical_Risk_Index']),
        'actual_delay':         int(row['Delay_Days']),
    }
    for _, row in test_sample.iterrows()
]

comparison = run_baseline_comparison(xgb_model, Q, test_scenarios)
print("\n── RL vs Baseline Comparison ──")
for k, v in comparison.items():
    print(f"  {k:<40} {v}")

"""##  Demo Test + Final JSON Export"""

import json

# ── Live demo simulation: 4 corridors × 3 weather scenarios ─────────────────
demo_scenarios = [
    # (corridor_id, weather_raw, geo_risk, label)
    (1, 0.85, 0.72, "Cyclone Warning — SIN→JebelAli"),
    (0, 0.55, 0.45, "Moderate Weather — SIN→Colombo"),
    (2, 0.20, 0.15, "Clear Skies — SIN→Mundra"),
    (3, 0.90, 0.80, "Severe Storm — SIN→NhavaSheva"),
]

print("=" * 65)
print("  MARKOV CHAINED — Live Inference Demo")
print("=" * 65)

demo_outputs = []
for corridor_id, weather_raw, geo_risk, label in demo_scenarios:
    result = run_inference(
        xgb_model,
        Q,
        corridor_id=corridor_id,
        weather_severity_raw=weather_raw,
        geopolitical_risk=geo_risk,
    )
    demo_outputs.append({'scenario': label, **result})

    print(f"\n  Scenario : {label}")
    print(f"  Action   : {result['action']}  (confidence: {result['confidence']:.0%})")
    print(f"  Cong Prob: {result['congestion_probability']:.2%}  [{result['congestion_level']}]")
    print(f"  Savings  : {result['delay_saved_hours']}h | ${result['cost_saved_usd']:,.0f} | {result['carbon_saved_tco2']} tCO₂")
    print(f"  Q-Values : {result['q_values']}")

# ── Export full pipeline artifacts ────────────────────────────────────────────
# 1. Retrained Q-table JSON (updated with synthetic augmentation)
q_table_export_v2 = {}
for s in range(env.n_states):
    c, w, cg = env.decode_state(s)
    key = f"{c}_{w}_{cg}"
    q_table_export_v2[key] = {
        'state_index':    s,
        'corridor':       CORRIDOR_MAP_INV[c],
        'weather':        WEATHER_MAP_INV[w],
        'congestion':     CONGESTION_MAP_INV[cg],
        'q_values': {
            'Maintain Course': round(float(Q[s, 0]), 6),
            'Slow Steam':      round(float(Q[s, 1]), 6),
            'Reroute':         round(float(Q[s, 2]), 6),
        },
        'optimal_action': ACTION_META[int(np.argmax(Q[s]))]['label']
    }

with open('q_table_v2.json', 'w') as f:
    json.dump(q_table_export_v2, f, indent=2)

# 2. Demo outputs JSON (hand to frontend team for hardcoded fallback)
with open('demo_outputs.json', 'w') as f:
    json.dump(demo_outputs, f, indent=2, default=str)

# 3. Pipeline config (backend team needs these thresholds)
pipeline_config = {
    'weather_thresholds':     {'Clear': [0, 0.33], 'Moderate': [0.33, 0.66], 'Severe': [0.66, 1.0]},
    'congestion_threshold':   0.5,
    'corridor_map':           CORRIDOR_MAP_INV,
    'feature_order': [
        'Geopolitical_Risk_Index', 'Weather_Severity_Index',
        'Inflation_Rate_Pct', 'Base_Lead_Time_Days',
        'Transportation_Mode_Enc', 'Route_Type_Enc',
        'Disruption_Event_Enc', 'Order_Weight_Kg', 'Congestion_Score'
    ],
    'action_meta': ACTION_META,
    'model_auc': 0.8325,
}

with open('pipeline_config.json', 'w') as f:
    json.dump(pipeline_config, f, indent=2)

print("\n\nArtifacts saved:")
print("  q_table_v2.json      → backend team (Q-table lookup)")
print("  demo_outputs.json    → frontend team (fallback hardcoded data)")
print("  pipeline_config.json → backend team (thresholds + feature order)")
print("  xgb_congestion_model.pkl → backend team (FastAPI model load)")

"""## V2 Optimisation — Reward Recalibration

Issue identified: V1 Q-table recommends Reroute universally (including Clear Skies,
low congestion corridors) because the base reward function gave Reroute unconditional
positive returns with no penalty for unnecessary intervention.

Fix: SupplyChainEnvV2 adds:
  - Penalty for Rerouting when congestion_prob < 0.4
  - Bonus for Slow Steam in moderate-risk band (0.35–0.65)
  - Live-demo fix: weather_severity_raw auto-maps to disruption_event_enc
    so XGBoost fires correctly without manual input at demo time.
"""

# ═══════════════════════════════════════════════════════════════
# FIX 1: Patch the reward function to penalise unnecessary reroutes
# ═══════════════════════════════════════════════════════════════

class SupplyChainEnvV2(SupplyChainEnv):
    """
    Overrides compute_reward with a smarter reward function.
    Key fix: Reroute is expensive when congestion is low → penalise it.
    """
    def compute_reward(self, action, congestion_prob, actual_delay):
        profile = self.ACTION_PROFILES[action]
        dt = profile['dt']
        dc = profile['dc'] / 15000.0
        de = profile['de'] / 10.0

        base_reward = -(self.W_TIME * dt + self.W_COST * dc + self.W_CARBON * de)

        # ── Penalty: unnecessary reroute when congestion is low ──────────────
        # This is the critical fix — rerouting on a clear day wastes cost/time
        if action == 2 and congestion_prob < 0.4:
            base_reward -= 3.0 * (0.4 - congestion_prob)  # scales: 0→-1.2, 0.1→-0.9

        # ── Penalty: maintaining course during high disruption ───────────────
        if action == 0 and congestion_prob > 0.6:
            base_reward -= 2.0 * congestion_prob * max(actual_delay, 1) * 0.1

        # ── Bonus: correct aggressive action when disruption is real ─────────
        if action == 2 and congestion_prob > 0.6:
            base_reward += 0.8

        # ── Bonus: slow steam is rational for moderate risk ──────────────────
        if action == 1 and 0.35 < congestion_prob < 0.65:
            base_reward += 0.4

        return float(base_reward)

# ═══════════════════════════════════════════════════════════════
# FIX 2: Patch inference to map weather → disruption_event_enc
# ═══════════════════════════════════════════════════════════════

def predict_congestion_probability_v2(
    xgb_model,
    corridor_id: int,
    weather_severity_raw: float,
    geopolitical_risk: float,
    base_lead_time: int = 12,
    transport_mode_enc: int = 1,
    order_weight_kg: int = 5000,
    inflation_rate: float = 3.0,
) -> float:
    """
    V2: automatically infers disruption_event_enc from weather severity.
    At demo time Open-Meteo gives wind speed → weather_severity_raw.
    We now use that to set disruption signal so XGBoost fires correctly.
    """
    # Map weather severity → disruption event encoding
    # This is the live-demo fix: no manual disruption signal needed
    if weather_severity_raw >= 0.66:
        disruption_event_enc = 2   # Severe Weather
    elif weather_severity_raw >= 0.33 and geopolitical_risk > 0.5:
        disruption_event_enc = 3   # Geopolitical (moderate weather + high geo risk)
    elif weather_severity_raw >= 0.33:
        disruption_event_enc = 1   # Port Congestion proxy
    else:
        disruption_event_enc = 0   # None

    congestion_score = (geopolitical_risk + disruption_event_enc / 3.0) / 2.0

    features = np.array([[
        geopolitical_risk,
        weather_severity_raw,
        inflation_rate,
        base_lead_time,
        transport_mode_enc,
        corridor_id,
        disruption_event_enc,
        order_weight_kg,
        congestion_score,
    ]])

    prob = float(xgb_model.predict_proba(features)[0, 1])
    return round(prob, 4)


# ═══════════════════════════════════════════════════════════════
# FIX 3: Retrain Q with V2 environment
# ═══════════════════════════════════════════════════════════════

env_v2 = SupplyChainEnvV2(df)

synthetic_episodes = generate_synthetic_episodes(5000)
all_episodes_v2 = env_v2.episodes + synthetic_episodes

Q2 = np.zeros((env_v2.n_states, env_v2.n_actions))
EPSILON = 1.0
rh = []

for ep in range(25000):
    state, cong_prob, actual_delay, _ = random.choice(all_episodes_v2)
    action = random.randint(0, 2) if random.random() < EPSILON else int(np.argmax(Q2[state]))
    reward = env_v2.compute_reward(action, cong_prob, actual_delay)
    Q2[state, action] += 0.1 * (reward + 0.95 * np.max(Q2[state]) - Q2[state, action])
    rh.append(reward)
    EPSILON = max(0.01, EPSILON * 0.9997)

print("V2 training complete.\n")

# ── Verify policy is now sensible ────────────────────────────────────────────
print("── V2 Policy Spot-check ──")
spot_checks = [
    (1, 2, 1, "SIN→JebelAli  | Severe  | High   → expect: Reroute"),
    (1, 1, 1, "SIN→JebelAli  | Moderate| High   → expect: Slow Steam or Reroute"),
    (0, 1, 0, "SIN→Colombo   | Moderate| Low    → expect: Slow Steam"),
    (2, 0, 0, "SIN→Mundra    | Clear   | Low    → expect: Maintain Course"),
    (3, 0, 0, "SIN→NhavaSheva| Clear   | Low    → expect: Maintain Course"),
]
for c, w, cg, label in spot_checks:
    s = env_v2._encode_state(c, w, cg)
    best = int(np.argmax(Q2[s]))
    print(f"  {label}")
    print(f"    → {ACTION_META[best]['label']}   Q={np.round(Q2[s], 3)}\n")

# ── Updated run_inference using V2 model + Q-table ───────────────────────────
def run_inference_v2(xgb_model, Q_table, corridor_id, weather_severity_raw, geopolitical_risk, **kwargs):
    cong_prob = predict_congestion_probability_v2(
        xgb_model, corridor_id, weather_severity_raw, geopolitical_risk, **kwargs
    )
    state_idx, corridor, weather_level, cong_level = encode_rl_state(
        corridor_id, weather_severity_raw, cong_prob
    )
    action_id, confidence = query_q_table(Q_table, state_idx)
    meta = ACTION_META[action_id]

    return {
        'action':                 meta['label'],
        'confidence':             round(confidence, 4),
        'congestion_probability': cong_prob,
        'congestion_level':       CONGESTION_MAP_INV[cong_level],
        'delay_saved_hours':      round(meta['delay_saved'] * (cong_prob + 0.3), 2),
        'cost_saved_usd':         round(meta['cost_saved']  * (cong_prob + 0.3), 2),
        'carbon_saved_tco2':      round(meta['carbon_saved']* (cong_prob + 0.3), 2),
        'state': {
            'index':      state_idx,
            'corridor':   CORRIDOR_MAP_INV[corridor],
            'weather':    WEATHER_MAP_INV[weather_level],
            'congestion': CONGESTION_MAP_INV[cong_level],
        },
        'q_values': {
            'Maintain Course': round(float(Q_table[state_idx, 0]), 4),
            'Slow Steam':      round(float(Q_table[state_idx, 1]), 4),
            'Reroute':         round(float(Q_table[state_idx, 2]), 4),
        }
    }

# ── Demo scenarios ────────────────────────────────────────────────────────────
demo_scenarios_v2 = [
    (1, 0.85, 0.72, "Cyclone Warning    — SIN→JebelAli"),
    (0, 0.55, 0.45, "Moderate Weather   — SIN→Colombo"),
    (2, 0.20, 0.15, "Clear Skies        — SIN→Mundra"),
    (3, 0.90, 0.80, "Severe Storm       — SIN→NhavaSheva"),
]

print("=" * 65)
print("  MARKOV CHAINED — V2 Inference Demo")
print("=" * 65)

demo_outputs_v2 = []
for corridor_id, weather_raw, geo_risk, label in demo_scenarios_v2:
    result = run_inference_v2(xgb_model, Q2, corridor_id, weather_raw, geo_risk)
    demo_outputs_v2.append({'scenario': label, **result})
    print(f"\n  Scenario : {label}")
    print(f"  Action   : {result['action']}  (confidence: {result['confidence']:.0%})")
    print(f"  Cong Prob: {result['congestion_probability']:.2%}  [{result['congestion_level']}]")
    print(f"  Savings  : {result['delay_saved_hours']}h | ${result['cost_saved_usd']:,.0f} | {result['carbon_saved_tco2']} tCO₂")

# ── Fixed baseline comparison ─────────────────────────────────────────────────
print("\n\n── V2 Baseline Comparison ──")
rl_r, base_r, rl_cost, rl_carbon = [], [], [], []
correct, total_disrupted = 0, 0

for scenario in test_scenarios:
    cp = predict_congestion_probability_v2(
        xgb_model,
        scenario['corridor_id'],
        scenario['weather_severity_raw'],
        scenario['geopolitical_risk'],
    )
    s, _, _, _ = encode_rl_state(scenario['corridor_id'], scenario['weather_severity_raw'], cp)
    delay = scenario.get('actual_delay', int(cp * 10))

    rl_action, _ = query_q_table(Q2, s)
    base_action   = 0

    rl_r.append(env_v2.compute_reward(rl_action, cp, delay))
    base_r.append(env_v2.compute_reward(base_action, cp, delay))
    rl_cost.append(ACTION_META[rl_action]['cost_saved'])
    rl_carbon.append(ACTION_META[rl_action]['carbon_saved'])

    if cp > 0.5:
        total_disrupted += 1
        if rl_action != 0:
            correct += 1

print(f"  RL avg reward       : {np.mean(rl_r):.4f}")
print(f"  Baseline avg reward : {np.mean(base_r):.4f}")
print(f"  Reward delta        : {np.mean(rl_r) - np.mean(base_r):+.4f}")
print(f"  RL total cost saved : ${sum(rl_cost):,.0f}")
print(f"  RL total CO₂ saved  : {sum(rl_carbon):.1f} tCO₂")
print(f"  Intervention rate   : {correct}/{total_disrupted} disrupted scenarios handled correctly")

# ── Save final artifacts ──────────────────────────────────────────────────────
with open('demo_outputs_v2.json', 'w') as f:
    json.dump(demo_outputs_v2, f, indent=2, default=str)

# Export V2 Q-table
q_export_v2 = {}
for s in range(env_v2.n_states):
    c, w, cg = env_v2.decode_state(s)
    q_export_v2[f"{c}_{w}_{cg}"] = {
        'corridor': CORRIDOR_MAP_INV[c], 'weather': WEATHER_MAP_INV[w],
        'congestion': CONGESTION_MAP_INV[cg],
        'q_values': {
            'Maintain Course': round(float(Q2[s,0]),6),
            'Slow Steam':      round(float(Q2[s,1]),6),
            'Reroute':         round(float(Q2[s,2]),6),
        },
        'optimal_action': ACTION_META[int(np.argmax(Q2[s]))]['label']
    }
with open('q_table_v2_final.json', 'w') as f:
    json.dump(q_export_v2, f, indent=2)

print("\nFinal artifacts saved: demo_outputs_v2.json, q_table_v2_final.json")

"""## V3"""

# ═══════════════════════════════════════════════════════════════
# FIX: SupplyChainEnvV3 — band-based reward (not penalty-based)
# ═══════════════════════════════════════════════════════════════

class SupplyChainEnvV3(SupplyChainEnv):
    """
    Reward is determined by whether the action matches the risk band.

    Risk bands based on congestion_prob:
      Low      < 0.35  → Maintain Course is correct
      Moderate 0.35–0.60 → Slow Steam is correct
      High     > 0.60  → Reroute is correct

    Wrong actions get negative rewards proportional to how wrong they are.
    """
    def compute_reward(self, action, congestion_prob, actual_delay):

        # ── Determine correct action for this risk level ──────────────────
        if congestion_prob < 0.35:
            correct_action = 0   # Maintain Course
            risk_band = 'low'
        elif congestion_prob < 0.60:
            correct_action = 1   # Slow Steam
            risk_band = 'moderate'
        else:
            correct_action = 2   # Reroute
            risk_band = 'high'

        # ── Base reward: correct action = +2.0, else scaled negative ─────
        if action == correct_action:
            reward = 2.0

            # Extra bonus for catching real delays
            if actual_delay > 0 and action in [1, 2]:
                reward += min(actual_delay * 0.1, 1.0)

        else:
            # Penalise proportional to how dangerous the mismatch is
            mismatch = abs(action - correct_action)  # 1 or 2 steps off

            if risk_band == 'high' and action == 0:
                # Worst case: maintain course in a crisis
                reward = -3.0 * congestion_prob * max(actual_delay, 1) * 0.15

            elif risk_band == 'low' and action == 2:
                # Unnecessary reroute on clear day — wasteful
                reward = -2.5 * (0.35 - congestion_prob) * 4

            else:
                # Off by one band — moderate penalty
                reward = -0.8 * mismatch

        return float(reward)


# ── Retrain V3 ────────────────────────────────────────────────────────────────
env_v3    = SupplyChainEnvV3(df)
synthetic = generate_synthetic_episodes(6000)
all_eps   = env_v3.episodes + synthetic

Q3        = np.zeros((env_v3.n_states, env_v3.n_actions))
EPSILON   = 1.0
rh3       = []

for ep in range(30000):
    state, cp, delay, _ = random.choice(all_eps)
    action = random.randint(0, 2) if random.random() < EPSILON else int(np.argmax(Q3[state]))
    reward = env_v3.compute_reward(action, cp, delay)
    Q3[state, action] += 0.1 * (reward + 0.95 * np.max(Q3[state]) - Q3[state, action])
    rh3.append(reward)
    EPSILON = max(0.01, EPSILON * 0.9997)

print("V3 training complete.\n")

# ── Convergence plot ──────────────────────────────────────────────────────────
smoothed = pd.Series(rh3).rolling(300).mean()
plt.figure(figsize=(12, 3))
plt.plot(smoothed, color='#2ecc71', linewidth=1.5)
plt.title('V3 Reward Convergence')
plt.xlabel('Episode')
plt.ylabel('Avg Reward')
plt.axhline(0, color='grey', linestyle='--', linewidth=0.8)
plt.tight_layout()
plt.show()

# ── Policy spot-check ─────────────────────────────────────────────────────────
print("── V3 Policy Spot-check ──")
spot_checks = [
    (1, 2, 1, "SIN→JebelAli  | Severe   | High    → expect: Reroute"),
    (1, 1, 1, "SIN→JebelAli  | Moderate | High    → expect: Reroute or SlowSteam"),
    (0, 1, 0, "SIN→Colombo   | Moderate | Low     → expect: Slow Steam"),
    (2, 0, 0, "SIN→Mundra    | Clear    | Low     → expect: Maintain Course"),
    (3, 0, 0, "SIN→NhavaSheva| Clear    | Low     → expect: Maintain Course"),
]
all_correct = True
for c, w, cg, label in spot_checks:
    s    = env_v3._encode_state(c, w, cg)
    best = int(np.argmax(Q3[s]))
    flag = "✓" if ACTION_META[best]['label'] != 'Reroute' or 'Severe' in label or 'High' in label else "✗"
    if flag == "✗":
        all_correct = False
    print(f"  {flag} {label}")
    print(f"      → {ACTION_META[best]['label']}   Q={np.round(Q3[s], 3)}\n")

print("Policy looks correct ✓" if all_correct else "Still issues — paste Q values above")

# ── V3 Demo ───────────────────────────────────────────────────────────────────
print("=" * 65)
print("  MARKOV CHAINED — V3 Inference Demo")
print("=" * 65)

demo_outputs_v3 = []
for corridor_id, weather_raw, geo_risk, label in demo_scenarios_v2:
    result = run_inference_v2(xgb_model, Q3, corridor_id, weather_raw, geo_risk)
    demo_outputs_v3.append({'scenario': label, **result})
    print(f"\n  Scenario : {label}")
    print(f"  Action   : {result['action']}  (confidence: {result['confidence']:.0%})")
    print(f"  Cong Prob: {result['congestion_probability']:.2%}  [{result['congestion_level']}]")
    print(f"  Savings  : {result['delay_saved_hours']}h | ${result['cost_saved_usd']:,.0f} | {result['carbon_saved_tco2']} tCO₂")

# ── Final baseline comparison ─────────────────────────────────────────────────
print("\n── V3 Baseline Comparison ──")
rl_r, base_r, rl_cost, rl_carbon = [], [], [], []
correct, total_disrupted = 0, 0

for scenario in test_scenarios:
    cp    = predict_congestion_probability_v2(
        xgb_model, scenario['corridor_id'],
        scenario['weather_severity_raw'], scenario['geopolitical_risk']
    )
    s, _, _, _ = encode_rl_state(scenario['corridor_id'], scenario['weather_severity_raw'], cp)
    delay = scenario.get('actual_delay', int(cp * 10))

    rl_action, _ = query_q_table(Q3, s)
    rl_r.append(env_v3.compute_reward(rl_action, cp, delay))
    base_r.append(env_v3.compute_reward(0, cp, delay))
    rl_cost.append(ACTION_META[rl_action]['cost_saved'])
    rl_carbon.append(ACTION_META[rl_action]['carbon_saved'])

    if cp > 0.5:
        total_disrupted += 1
        if rl_action != 0:
            correct += 1

print(f"  RL avg reward       : {np.mean(rl_r):.4f}")
print(f"  Baseline avg reward : {np.mean(base_r):.4f}")
print(f"  Reward delta        : {np.mean(rl_r) - np.mean(base_r):+.4f}")
print(f"  RL total cost saved : ${sum(rl_cost):,.0f}")
print(f"  RL total CO₂ saved  : {sum(rl_carbon):.1f} tCO₂")
print(f"  Intervention rate   : {correct}/{total_disrupted} disrupted scenarios handled correctly")

# ── Save final artifacts ──────────────────────────────────────────────────────
with open('demo_outputs_v3.json', 'w') as f:
    json.dump(demo_outputs_v3, f, indent=2, default=str)

q_export_v3 = {}
for s in range(env_v3.n_states):
    c, w, cg = env_v3.decode_state(s)
    q_export_v3[f"{c}_{w}_{cg}"] = {
        'corridor':       CORRIDOR_MAP_INV[c],
        'weather':        WEATHER_MAP_INV[w],
        'congestion':     CONGESTION_MAP_INV[cg],
        'q_values': {
            'Maintain Course': round(float(Q3[s,0]),6),
            'Slow Steam':      round(float(Q3[s,1]),6),
            'Reroute':         round(float(Q3[s,2]),6),
        },
        'optimal_action': ACTION_META[int(np.argmax(Q3[s]))]['label']
    }

with open('q_table_v3_final.json', 'w') as f:
    json.dump(q_export_v3, f, indent=2)

print("\nFinal artifacts: demo_outputs_v3.json  q_table_v3_final.json")
print("Hand q_table_v3_final.json to backend — this is the production Q-table.")